os: Windows Server 2012 R2

clone_depth: 1
version: 4.0.0.{build}

services:
  - mssql2012sp1

environment:
  resizer_test_mongo_db: mongodb://localhost:27017/resizer2
  
  fb_nuget_url: https://www.myget.org/F/imazen-nightlies/
  fb_nuget_key:
    secure: GmqIvIvIOiwNxjW+z+vL9tbVD9vqUdB+0HsdDhnhR3km4WLZwpLcQT41D7xlhgFX
  
  fb_s3_bucket: imazen-test
  fb_s3_id:
    secure: Qi7mSLHr94NfJaH0CzQSVPEl1peaOoJADyfHwiVtJzo=
  fb_s3_key:
    secure: RP9hZqS0Pt2SLeias0iZpt2E9OltVX8OPfhWnGET6fQKZ05Fy6y0z1JcWWvONhF0
  
  # a nuget url should go here eventually
  fb_nuget_rel_url: https://www.myget.org/F/resizer-rel-test/
  fb_nuget_rel_key:
    secure: GmqIvIvIOiwNxjW+z+vL9tbVD9vqUdB+0HsdDhnhR3km4WLZwpLcQT41D7xlhgFX
  
  fb_s3_rel_bucket: imazen-test-rel
  fb_s3_rel_id:
    secure: Qi7mSLHr94NfJaH0CzQSVPEl1peaOoJADyfHwiVtJzo=
  fb_s3_rel_key:
    secure: RP9hZqS0Pt2SLeias0iZpt2E9OltVX8OPfhWnGET6fQKZ05Fy6y0z1JcWWvONhF0
  
  fb_pub_url: https://s3.amazonaws.com/imazen-test
  
  fb_imageserver_repo: github.com/imazen/resizer-images.git
  fb_imageserver_path: resizer-images
  fb_imageserver_branch: develop
  # should be set to master when resizer-images is updated
  fb_imageserver_rel_branch: develop
  
  imageserver_user: resizer-bot
  imageserver_mail:
    secure: Ki6EM9c3O3ioPTfrbWZMtQ==
  imageserver_token:
    secure: ShmRBY5OrRHdAfze81bt2iqFr+6JHh0FAnApuB4d+bGgksdicVa/BJinCQyS/92B

before_build:
  
  # add imageserver key
  - git config --global push.default simple
  - git config --global credential.helper wincred
  - git config --global user.name "%imageserver_user%"
  - git config --global user.email "%imageserver_mail%"
  - git clone --depth 1 --branch %fb_imageserver_branch% https://%imageserver_user%:%imageserver_token%@%fb_imageserver_repo% Tools\%fb_imageserver_path%
  
  # set up mongodb
  - ps: md $env:temp\mongo\data
  - ps: Push-Location $env:temp\mongo
  - ps: Invoke-WebRequest https://s3.amazonaws.com/public-unit-test-resources/mongodb/mongod.exe.zip -OutFile mongodb.zip
  - 7z x -o.\ mongodb.zip
  - mongod.exe --logpath=mongo.log --dbpath=. --smallfiles --install
  - ps: Start-Sleep -Seconds 5
  - ps: net start mongodb
  - ps: Pop-Location

build_script:
  - cd Tools
  - builder update
  - builder do_all
  - cd ..

test: off
